module.exports = function(app)
{
	app.get('/',function(req,res){
                res.render('index.html');
        });
	app.get('/index.html',function(req,res){
		res.render('index.html');
	});
	app.get('/Finish.html',function(req,res){
		res.render('Finish.html');
	});
	app.get('/Register.html',function(req,res){
		res.render('Register.html');
	});
	app.get('/Important.html',function(req,res){
                res.render('Important.html');
        });
	app.get('/Recent.html',function(req,res){
                res.render('Recent.html');
        });
	app.get('/Trash.html',function(req,res){
                res.render('Trash.html');
        });
}
